---
name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on:  # NOLINT
  push:
    tags:
      - "*"

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/statick-tex
    permissions:
      id-token: write
      pages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Build a binary wheel and a source tarball
        run: |
          pip install -q build
          python -m build

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Sphinx lint
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"

      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          publish_branch: gh-pages
